spring:
    profiles:
      active: dev
#  datasource:
#    username: xxx
#    password: xxx
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:/url?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&serverTimezone=GMT&useSSL=false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.webpom.moments.entity #实体类取别名
  configuration:
      ## 下划线转驼峰配置
    map-underscore-to-camel-case: true
## 显示dao 执⾏sql语句
logging:
  level:
    com.ppl.springboot.dao: debug # 改成你的dao接口文件所在包路径可以打印出sql语句
com:
  webpom:
    adminList: 6330340b40859ace2d37ee4d,63304f26ea3643d7a12f286a,6330340b40859ace2d37ee4d